services:
  ta-backend-api:
    image: ta-backend-api
    container_name: ta-backend-api
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.docker
    ports:
      - '8000:8000'
    networks:
      - ta-backend-network

  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025
    networks:
      - ta-backend-network

networks:
  ta-backend-network:
    driver: bridge
