export enum ReservationStatus {
  ORDER_CREATED = 'ORDER_CREATED',
  ORDER_WAITING_PAYMENT = 'ORDER_WAITING_PAYMENT',
  ORDER_PAID_PARTIAL = 'ORDER_PAID_PARTIAL',
  ORDER_PAID_COMPLETED = 'ORDER_PAID_COMPLETED',
  ORDER_PROCESSING = 'ORDER_PROCESSING',
  ORDER_COMPLETED = 'ORDER_COMPLETED',
  ORDER_CANCELED = 'ORDER_CANCELED',
  ORDER_FAIL = 'ORDER_FAIL',
  REFUND_PENDING = 'REFUND_PENDING',
  REFUND_COMPLETED = 'REFUND_COMPLETED',
  REFUND_FAIL = 'REFUND_FAIL',
}
// Dispute raised: ORDER_COMPLETED
// Dispute resolved: ORDER_COMPLETED -> REFUND_PENDING -> REFUND_COMPLETED
// Dispute rejected: still ORDER_COMPLETED
// The status of dispute will stored onchain

export enum DisputeStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED_FAVOR_GUEST = 'RESOLVED_FAVOR_GUEST',
  RESOLVED_FAVOR_HOST = 'RESOLVED_FAVOR_HOST',
  RESOLVED_COMPROMISE = 'RESOLVED_COMPROMISE',
}

export enum ListingStatus {
  LISTING_DRAFT = 'LISTING_DRAFT',
  LISTING_IN_REVIEW = 'LISTING_IN_REVIEW',
  LISTING_REJECTED = 'LISTING_REJECTED',
  LISTING_COMPLETED = 'LISTING_COMPLETED',
  LISTING_DELETED = 'LISTING_DELETED',
}
